Clean up ReflectConfigUtil class
- Call discoverDTOs once instead of once for every JAR
- Catch NoClassDefFoundError when processing activator
- Searching method should use getDeclaredMethod with parameter types when possible

- Remove atomos.tests.testbundles.substrate.main artifact
- Use AtomosLauncher directly in example